production:
  adapter: mysql2
  database: geofeelings_prod
  username: 
  password:

development:
  adapter: mysql2
  database: geofeelings_devel
  username: 
  password:

test:
  adapter: mysql2
  database: geofeelings_test
  username:
  password:
